import type { KatalogEintrag } from "@/lib/katalog/types";

/** Beispieldaten für einen Malerbetrieb – alle Kategorien und Übersetzungen. */
export const sampleKatalog: KatalogEintrag[] = [
  {
    id: "malerarbeiten-wandflaeche",
    de: "Malerarbeiten Wandfläche",
    uebersetzungen: { de: "Malerarbeiten Wandfläche", tr: "Duvar boyama", ar: "طلاء الجدران" },
    einheit: "m²",
    preisCents: 1200,
    kategorie: "Wand & Decke",
    verwendungen: 12,
  },
  {
    id: "tapete-entfernen",
    de: "Tapete entfernen",
    uebersetzungen: { de: "Tapete entfernen", tr: "Duvar kağıdı sökme", ar: "إزالة ورق الجدران" },
    einheit: "m²",
    preisCents: 450,
    kategorie: "Vorbereitung",
    verwendungen: 8,
  },
  {
    id: "deckenanstrich",
    de: "Deckenanstrich",
    uebersetzungen: { de: "Deckenanstrich", tr: "Tavan boyama", ar: "طلاء السقف" },
    einheit: "m²",
    preisCents: 1000,
    kategorie: "Wand & Decke",
    verwendungen: 9,
  },
  {
    id: "tapezieren",
    de: "Tapezieren",
    uebersetzungen: { de: "Tapezieren", tr: "Duvar kağıdı kaplama", ar: "تركيب ورق الجدران" },
    einheit: "m²",
    preisCents: 1400,
    kategorie: "Wand & Decke",
    verwendungen: 6,
  },
  {
    id: "fassadenanstrich",
    de: "Fassadenanstrich",
    uebersetzungen: { de: "Fassadenanstrich", tr: "Cephe boyama", ar: "طلاء الواجهة" },
    einheit: "m²",
    preisCents: 2800,
    kategorie: "Fassade",
    verwendungen: 4,
  },
  {
    id: "lackierarbeiten-tueren",
    de: "Lackierarbeiten Türen",
    uebersetzungen: { de: "Lackierarbeiten Türen", tr: "Kapı lake / boya", ar: "طلاء الأبواب" },
    einheit: "Stk.",
    preisCents: 9500,
    kategorie: "Lackierung",
    verwendungen: 7,
  },
  {
    id: "grundierung",
    de: "Grundierung auftragen",
    uebersetzungen: { de: "Grundierung auftragen", tr: "Astar sürme", ar: "طبقة أساس" },
    einheit: "m²",
    preisCents: 650,
    kategorie: "Vorbereitung",
    verwendungen: 11,
  },
  {
    id: "spachtelarbeiten",
    de: "Spachtelarbeiten",
    uebersetzungen: { de: "Spachtelarbeiten", tr: "Macunlama", ar: "أعمال المعجون" },
    einheit: "m²",
    preisCents: 800,
    kategorie: "Vorbereitung",
    verwendungen: 5,
  },
  {
    id: "treppenhaus-streichen",
    de: "Treppenhaus streichen",
    uebersetzungen: { de: "Treppenhaus streichen", tr: "Merdiven boyama", ar: "طلاء السلم" },
    einheit: "Pauschal",
    preisCents: 38000,
    kategorie: "Wand & Decke",
    verwendungen: 3,
  },
  {
    id: "fussleisten-lackieren",
    de: "Fußleisten lackieren",
    uebersetzungen: { de: "Fußleisten lackieren", tr: "Süpürgelik boya", ar: "طلاء الحاشية" },
    einheit: "lfm",
    preisCents: 750,
    kategorie: "Lackierung",
    verwendungen: 5,
  },
  {
    id: "putzausbesserung",
    de: "Putzausbesserung",
    uebersetzungen: { de: "Putzausbesserung", tr: "Sıva tamiratı", ar: "إصلاح الجبس" },
    einheit: "m²",
    preisCents: 1800,
    kategorie: "Vorbereitung",
    verwendungen: 4,
  },
  {
    id: "materialpauschale",
    de: "Materialpauschale",
    uebersetzungen: { de: "Materialpauschale", tr: "Malzeme paketi", ar: "رسوم المواد" },
    einheit: "Pauschal",
    preisCents: 8500,
    kategorie: "Sonstiges",
    verwendungen: 15,
  },
];
